package ca.jrvs.apps.trading.controller;

import ca.jrvs.apps.trading.dao.TraderDao;
import ca.jrvs.apps.trading.model.domain.Account;
import ca.jrvs.apps.trading.model.domain.Trader;
import ca.jrvs.apps.trading.model.view.TraderAccountView;
import ca.jrvs.apps.trading.service.FundTransferService;
import ca.jrvs.apps.trading.service.RegisterService;
import ca.jrvs.apps.trading.util.ResponseExceptionUtil;
import ca.jrvs.apps.trading.util.TradingUtil;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Date;
import java.time.LocalDate;

@Api(value = "Trader", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
@Controller
@RequestMapping("/trader")
public class TraderController {

    private RegisterService registerService;
    private FundTransferService fundService;

    @Autowired
    public TraderController(RegisterService registerService, FundTransferService fundService) {
        this.registerService = registerService;
        this.fundService = fundService;
    }

    @ApiOperation(value = "Create a trader and associated account")
    @ResponseStatus(HttpStatus.CREATED)
    @ResponseBody
    @PostMapping(path = "/firstname/{firstname}/lastname/{lastname}/dob/{dob}/country/{country}/email/{email}",
            produces = {MediaType.APPLICATION_JSON_UTF8_VALUE})
    public TraderAccountView createTrader(@PathVariable String firstname, @PathVariable String lastname,
                                          @PathVariable @DateTimeFormat(pattern = TradingUtil.DATE_PATTERN) LocalDate dob,
                                          @PathVariable String country, @PathVariable String email) {
        try {
            Trader trader = new Trader();
            trader.setFirst_name(firstname);
            trader.setLast_name(lastname);
            trader.setCountry(country);
            trader.setEmail(email);
            trader.setDob(Date.valueOf(dob));
            return registerService.createTraderAndAccount(trader);
        } catch (Exception e) {
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Create trader and account with data transfer object")
    @ResponseStatus(HttpStatus.CREATED)
    @ResponseBody
    @PostMapping(path = "/")
    public TraderAccountView createTrader(@RequestBody Trader trader) {
        try {
            return registerService.createTraderAndAccount(trader);
        } catch (Exception e) {
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Deposit funds to an existing account")
    @ResponseStatus(HttpStatus.ACCEPTED)
    @ResponseBody
    @PutMapping(path = "/deposit/accountId/{accountId}/amount/{amount}", produces = {MediaType.APPLICATION_JSON_UTF8_VALUE})
    public Account depositFunds(@PathVariable int accountId, @PathVariable double amount) {
        try {
            return fundService.deposit(accountId, amount); // "TraderId and AccountId are auto generated by the database, and they should be identical"
        } catch (Exception e) {
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Withdraw funds from an existing account")
    @ResponseStatus(HttpStatus.ACCEPTED)
    @ResponseBody
    @PutMapping(path = "/withdraw/accountId/{accountId}/amount/{amount}", produces = {MediaType.APPLICATION_JSON_UTF8_VALUE})
    public Account withdrawFunds(@PathVariable int accountId, @PathVariable double amount) {
        try {
            return fundService.withdraw(accountId, amount); // "TraderId and AccountId are auto generated by the database, and they should be identical"
        } catch (Exception e) {
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }

    @ApiOperation(value = "Delete a trader, its associated account & security order, given that the trader has no existing positions")
    @ResponseStatus(HttpStatus.ACCEPTED)
    @DeleteMapping(path = "/traderId/{traderId}")
    public void deleteTrader(@PathVariable int traderId) {
        try {
            registerService.deleteTraderById(traderId);
        } catch (Exception e) {
            throw ResponseExceptionUtil.getResponseStatusException(e);
        }
    }
}
